#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the cutTheSticks function below.
def cutTheSticks(arr):

    sticks_cut = []
    
    while(arr):
        sticks_cut.append(len(arr))
        length_of_cut = min(arr)
        arr = [i for i in arr if i != length_of_cut]
        arr = [x - length_of_cut for x in arr]
    
    return sticks_cut


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
