#!/bin/python3

import math
import os
import random
import re
import sys
import string

# Complete the designerPdfViewer function below.
def designerPdfViewer(h, word):
    length = len(word)
    new_list = []

    for i in word:
        new_list.append(h[string.ascii_lowercase.index(i)])

    new_list.sort()
    elem = new_list[-1]
    return elem*length


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = list(map(int, input().rstrip().split()))

    word = input()

    result = designerPdfViewer(h, word)

    fptr.write(str(result) + '\n')

    fptr.close()
