#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c, k):
    i = 0
    e = 100
    while((i+k)%n!=0):
        #i = (i+k)%n
        if(c[(i+k)%n]==0):
            e = e-1
        else:
            e = e-3
        print(e)
        i = (i+k)%n
        
    if(c[0]==0):
        e = e-1
    else:
        e = e-3
    return e

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c, k)

    fptr.write(str(result) + '\n')

    fptr.close()
