#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the permutationEquation function below.
def permutationEquation(p):
    j = 1
    output = []
    while(j<=len(p)):
        #val1 = p.index(j)
        #val2 = val1+1
        #print(val2)
        val = p.index(p.index(j)+1)+1
        #val4 = val3+1
        #print(val4)
        j = j+1
        output.append(val)
    return output

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
