#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    day_starts_with = 5 
    i = 0
    cumulative = 0
    while (i < n):
        liked = day_starts_with//2
        cumulative = cumulative + liked
        day_starts_with = liked * 3
        i = i+1
    return cumulative


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
