#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumDistances function below.
def minimumDistances(a):
    res = sys.maxsize
    dic = {}
    for i in range(0,len(a)):
        if(a[i] not in dic):
            dic[a[i]] = i
        else:
            res = min(res, i - dic[a[i]])
            dic[a[i]] = i  
    if(res < sys.maxsize):
        return res
    else:
        return -1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    a = list(map(int, input().rstrip().split()))

    result = minimumDistances(a)

    fptr.write(str(result) + '\n')

    fptr.close()
