#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the insertionSort1 function below.
def insertionSort1(n, arr):
    stored_val = arr[n-1]
    i = n-2
    while(i>=0):
        if(arr[i]>stored_val):
            arr[i+1]=arr[i]
            print(" ".join(str(j) for j in arr))
        else:
            arr[i+1]=stored_val
            print(" ".join(str(j) for j in arr))
            return
        i=i-1
    arr[0] = stored_val
    print(" ".join(str(j) for j in arr))
    return 


if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
